Feature home
guiromao87/cheeper pull request #13
Opened 2020-07-19 21:42 UTC by guiromao87

2020-07-19 21:42 UTC, guiromao87 commented
Pooooooorra, esqueci de mudar a branch base  de master para beach hot-fix!

2020-07-19 21:43 UTC, guiromao87 commented
Mas só tem um commit, que é o translate pt-br, passando as labels de tela pra portugues

2020-07-19 22:03 UTC, guiromao87 commented on src/main/resources/templates/home.html
> +                <span th:text="${#temporals.format(cheep.date, 'dd-MM-yy HH:mm')}" />: <b><span th:text="${cheep.message}" /></b>
Eu formatei na view pra manter LocalDateTime no banco caso precise trabalhar diretamente com as datas mais pra frente e estou dando um LocalDateTime.now() quando cria o cheep

2020-07-21 19:58 UTC, mariofts requested changes

2020-07-21 19:58 UTC, mariofts commented on src/main/java/com/study/cheeper/controller/CheepController.java
> +        Cheep cheep = newCheepForm.toCheep(userRepository);
Eu fiz um comentário lá na classe `NewCheepForm` sobre essa parte, resumindo, acho que você deveria passar o autor, e não o repo.

2020-07-21 19:58 UTC, mariofts commented on src/main/java/com/study/cheeper/controller/HomeController.java
> +        mv.addObject("cheep", cheepRepository.findAll());
Olhando pelo outro PR eu entendo que nesse ponto você está trazendo todos por não ter um motivo pra fazer o filtro 👍

2020-07-21 19:58 UTC, mariofts commented on src/main/java/com/study/cheeper/controller/HomeController.java
> +        mv.addObject("autor",user);
Aqui podemos ver se faz sentido passar o mesmo objeto de domínio para a view, tem uns pontos a considerar, tipo a view poder chamar qualquer coisa desse objeto, e as refatorações serem um pouco mais complexas  em jps e html

2020-07-21 19:58 UTC, mariofts commented on src/main/java/com/study/cheeper/controller/HomeController.java
> +    public ModelAndView home() {
Olhando para o método `defaultHome()`, se for só pelos diferentes paths, o `GetMapping` recebe um array, ai você poderia ter só um método:

```suggestion
@GetMapping(value={"/", "/home"})
public ModelAndView home() {
```

2020-07-21 19:58 UTC, mariofts commented on src/main/java/com/study/cheeper/model/User.java
> +    private List<Cheep> cheepers = new ArrayList<>();
bem trick essa relação, com o tempo  o user pode ter muitos cheeps, e se em algum ponto do código essa lista trigar o lazyload vai carregar tudo para a memória. Acho que vale pensarmos se devemos manter para facilitar ou remover

2020-07-21 19:58 UTC, mariofts commented on src/main/java/com/study/cheeper/model/form/NewCheepForm.java
> +    private Integer idAutor;
Não acho que deveriamos receber o ID do autor da página. Sabemos que quem está preenchendo o form é o usuário logado, então porque receber esse dado como parâmetro?

Se nos descuidarmos, podemos estar abrindo uma falha de segurança que permitiria um usuário fazer cheeps em nome de outro usuário.

2020-07-21 19:58 UTC, mariofts commented on src/main/java/com/study/cheeper/model/form/NewCheepForm.java
> +    public Cheep toCheep(UserRepository userRepository) {
com base no comentário de cima, podemos aqui receber o usuário logado de fora, e só preencher no cheep para poder salvar

2020-07-21 19:58 UTC, mariofts commented on src/main/java/com/study/cheeper/model/form/NewCheepForm.java
> +        Optional<User> autor = userRepository.findById(this.idAutor);
Fazendo a alteração de cima até evitamos ter que validar o usuário. Se ele está logado, logo existe na base :)

2020-07-21 19:58 UTC, mariofts commented on src/main/java/com/study/cheeper/model/form/NewCheepForm.java
> +        cheep.setAutor(autor.get());
Entendo o contexto que você só fez o código para ser o mais fácil, mas vou comentar só pra lembrar no papo: 

No optional, chamar o `.get` sem o `.isPresent` é meio que a mesma coisas de usar o objeto sem ver se ele está null. Só estamos trocando o `NPE` por um ÌllegalState`

2020-07-21 19:58 UTC, mariofts commented on src/main/resources/db/migration/V005__create_and_populate_cheep_table.sql
> +CREATE TABLE cheep (id bigint not null auto_increment primary key, date datetime(6), message varchar(255), autor_id integer);
Precisamos ver o tamanho da mensagem, nem lembro quantos caracteres é no twitter ultimamente 😛

2020-07-21 19:58 UTC, mariofts commented on src/main/resources/templates/home.html
> +        <input type="hidden" th:value="${autor.id}" name="idAutor" />
Remover baseado no comentário do `NewCheepForm`

2020-07-21 19:58 UTC, mariofts commented on src/main/resources/templates/home.html
> +                <span th:text="${#temporals.format(cheep.date, 'dd-MM-yy HH:mm')}" />: <b><span th:text="${cheep.message}" /></b>
Acho de boa formatar na view, só pensar se vale passar o formato como você fez ou se tem uma forma mais simples. Acho difícil, mas vale a olhada

2020-07-21 19:58 UTC, mariofts commented on src/main/java/com/study/cheeper/controller/CheepController.java
> +        cheepRepository.delete(id);
Aqui precisa validar se o autor do cheep é o cara logado, pra evitar problemas de uma pessoa deletar os cheeps da outra

2020-07-21 19:58 UTC, mariofts commented on src/main/resources/templates/login.html
> +    <h2>Rede Social - Creeper</h2>
Creeper?
![image](https://user-images.githubusercontent.com/300276/88100714-4fe05180-cb73-11ea-8500-a7ac3915f906.png)

2020-07-21 21:19 UTC, mariofts commented on src/main/java/com/study/cheeper/model/Cheep.java
> +    private LocalDateTime date = LocalDateTime.now();
Aqui é legal mudar o nome do campo apra `creationDate`?

2020-07-21 21:24 UTC, mariofts commented on src/main/java/com/study/cheeper/model/User.java
> +    private List<Cheep> cheepers = new ArrayList<>();
Inclusive, é cheeps

2020-07-21 21:25 UTC, mariofts commented on src/main/java/com/study/cheeper/controller/HomeController.java
> +        mv.addObject("cheep", cheepRepository.findAll());
cheeps

2020-07-21 22:05 UTC, mariofts commented on src/main/java/com/study/cheeper/controller/CheepController.java
> +        cheepRepository.delete(id);
```
Cheeps toDelete = cheepRepository .find(id);
if(toDelete.isOwnedBy(loggedUser)){ //eu só posso deletar meus cheeps
  cheepRepository.delete(id);
}

2020-07-21 22:09 UTC, mariofts commented on src/main/java/com/study/cheeper/controller/CheepController.java
> +        cheepRepository.delete(id);
Na classe Cheep
```
boolean isOwnedBy(User user){
  return this.author.equals(user);
}

2020-07-22 23:59 UTC, guiromao87 commented on src/main/resources/db/migration/V005__create_and_populate_cheep_table.sql
> +CREATE TABLE cheep (id bigint not null auto_increment primary key, date datetime(6), message varchar(255), autor_id integer);
280

2020-07-23 00:37 UTC, guiromao87 commented on src/main/java/com/study/cheeper/model/Cheep.java
> +    private LocalDateTime date = LocalDateTime.now();
por ele ser um LocalDatetime faz sentido deixar só creation?

2020-07-23 01:01 UTC, guiromao87 commented on src/main/resources/templates/home.html
> +                <span th:text="${#temporals.format(cheep.date, 'dd-MM-yy HH:mm')}" />: <b><span th:text="${cheep.message}" /></b>
Aqui valeria formater na saída do CheepDto(quando eu criar um) ?
Ai não alteraria no domínio e já mandaria formatado pra tela

2020-07-24 02:16 UTC, merged

2020-07-25 18:35 UTC, guiromao87 commented on src/main/resources/templates/home.html
> +                <span th:text="${#temporals.format(cheep.date, 'dd-MM-yy HH:mm')}" />: <b><span th:text="${cheep.message}" /></b>
fiz um método no DTO que retorna a data formatada. Coloquei apenas getFormattedDate() mas poderia ate ser algo tipo getPTFormatDateTime(), dai caso tenham outras formatações...