initial profile page
guiromao87/cheeper pull request #14
Opened 2020-07-21 11:55 UTC by guiromao87

2020-07-21 13:33 UTC, guiromao87 commented on src/main/resources/templates/profile.html
> +        </form>
Aqu ieu precisava mandar o id do usuário para a página de edit, com link ficaria amostra na url então coloquei em um form pra mandar hidden, não sei se foi a melhor solução

2020-07-21 18:09 UTC, guiromao87 commented on src/main/resources/application.yml
> +    region: ${REGION}
Aqui eu gerei um usuario na aws que me deu access e secret e coloquei como env var no intelliJ

2020-07-21 20:50 UTC, mariofts requested changes

2020-07-21 20:50 UTC, mariofts commented on pom.xml
> +			<version>1.11.822</version>
Uma opção aqui seria usar o spring-aws, você preferiu fazer a integração você mesmo por algum motivo?

2020-07-21 20:50 UTC, mariofts commented on src/main/java/com/study/cheeper/controller/HomeController.java
> +        mv.addObject("cheep", cheepRepository.findByAutorId(user.getId()));
Essa home é a página do perfil então? Só vão aparecer os cheeps do próprio perfil, é isso?

2020-07-21 20:50 UTC, mariofts commented on src/main/java/com/study/cheeper/controller/ProfileController.java
> +    public ModelAndView profile(@PathVariable("id") int id) {
Pensando na interface de uso, acho que esquecemos de colocar um handle (`@fulano`) para os usuários. Aqui o handle deveria ser o parâmetro, e não o id 🤦

2020-07-21 20:50 UTC, mariofts commented on src/main/java/com/study/cheeper/controller/ProfileController.java
> +        mv.addObject("user", optional.get());
mesma conversa de colcor o objeto de domínio na view, etc...

2020-07-21 20:50 UTC, mariofts commented on src/main/resources/application.yml
> +    region: ${REGION}
boa!

2020-07-21 20:50 UTC, mariofts commented on src/main/resources/templates/edit.html
> +    <h2>Edit profile</h2>
Aqui acho que era pra ser em português

2020-07-21 20:50 UTC, mariofts commented on src/main/resources/templates/profile.html
> +    <title>Profile</title>
purtuguês

2020-07-21 20:50 UTC, mariofts commented on src/main/resources/templates/404.html
> +    <title>Title</title>
```sugestion
    <title>Não encontrado</title>
```

2020-07-22 23:47 UTC, guiromao87 commented
commit ee9deac do upload é apenas funcionalidade, ele puxa a foto do s3 e troca mas ainda falta validar e tratar exception

2020-07-23 01:03 UTC, guiromao87 commented on src/main/java/com/study/cheeper/controller/HomeController.java
> +        mv.addObject("cheep", cheepRepository.findByAutorId(user.getId()));
isso

2020-07-23 01:03 UTC, guiromao87 commented on src/main/java/com/study/cheeper/controller/HomeController.java
> +        mv.addObject("cheep", cheepRepository.findByAutorId(user.getId()));
tinha feito findAll antes pra testar a tela

2020-07-23 01:05 UTC, guiromao87 commented on src/main/java/com/study/cheeper/controller/ProfileController.java
> +    public ModelAndView profile(@PathVariable("id") int id) {
aqui não entendi

2020-07-23 01:15 UTC, guiromao87 commented on pom.xml
> +			<version>1.11.822</version>
Lembrar de falar disso

2020-07-23 22:34 UTC, guiromao87 commented on src/main/java/com/study/cheeper/service/ProfileService.java
> +        user.setImage(bucketUrl + image.getOriginalFilename());
aqui pode ter replace da imagem

2020-07-24 02:17 UTC, merged