Security config by database
guiromao87/cheeper pull request #3
Opened 2020-07-13 19:44 UTC by guiromao87

2020-07-14 18:39 UTC, mariofts requested changes

2020-07-14 18:39 UTC, mariofts commented on src/main/java/com/study/cheeper/CheeperApplication.java
Faltou limpar os imports aqui

2020-07-14 18:39 UTC, mariofts commented on src/main/java/com/study/cheeper/config/SecurityConfig.java
> +    /* precisa ter esse bean mesmo que não use */
hum, ele não deve ter um default, deve ser pra forçar você a escolher um algoritmo mesmo

2020-07-14 18:39 UTC, mariofts commented on src/main/java/com/study/cheeper/controller/TesteController.java
> +    public String cadastra() { return "/cadastra.html"; }
Tem como você definir a extensão padrão, mudando o `viewresolver` se não em engano

2020-07-14 18:39 UTC, mariofts commented on src/main/java/com/study/cheeper/model/User.java
> +    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
boa, sempre bom escoler a estratégia e não deixar no `Auto`, pois isso pode mudar de banco para banco e inclusive entre versões do Mysql.

Tem um lance de performance relacionado ao que se escolhe aqui, mas apenas em casos extremos.

2020-07-14 18:39 UTC, mariofts commented on src/main/java/com/study/cheeper/model/User.java
> +     return null;
Legal sempre que o retorno for uma coleção, sempre devolver com um `Collections.emptyList()` no caso de não ter nada pra retornar.

Assim, você evita que quem chamou esse método tenha que testar se é `null` antes de testar se está vazia, é mais uma boa prática mesmo.

2020-07-14 18:39 UTC, mariofts commented on src/main/java/com/study/cheeper/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Integer> {
Faltou um `@Repository` aqui não?

2020-07-14 19:47 UTC, guiromao87 commented on src/main/java/com/study/cheeper/CheeperApplication.java
O IntelliJ escondeu e não me atentei!

2020-07-14 19:47 UTC, guiromao87 commented on src/main/java/com/study/cheeper/config/SecurityConfig.java
> +    /* precisa ter esse bean mesmo que não use */
ah sim!

2020-07-14 19:49 UTC, guiromao87 commented on src/main/java/com/study/cheeper/model/User.java
> +     return null;
uhum! vacilei

2020-07-14 21:00 UTC, mariofts commented
Refs #4

2020-07-15 16:42 UTC, guiromao87 commented on src/main/java/com/study/cheeper/controller/TesteController.java
> +    public String cadastra() { return "/cadastra.html"; }
Funcionou o item 17! https://frontbackend.com/thymeleaf/thymeleaf-default-spring-boot-application-properties

2020-07-17 22:05 UTC, mariofts approved these changes

2020-07-17 22:07 UTC, mariofts commented
esse resolves #4

2020-07-17 22:08 UTC, mariofts commented
closes #6

2020-07-17 22:09 UTC, merged